### ISSUE TITLE
Spotify.js Missing, Files Not Finished

### ISSUE THREAD

**Issue by jlag34** [MetalH47K/jammming#1]
I'm not sure if this was meant to be passed in. Your Spotify.js file is missing and there is little to no React in your pages.

**Comment by MetalH47K** [comment]
I thought I had to submit by a due date and this was as far as I had gotten. I have now completed up to step 80. I am having trouble with the Spotify.js steps.

**Comment by MetalH47K** [comment]
All files updated. Project Completed.
